### ISSUE TITLE
Wyze Cam V2 (T20 XiaoFang) doesn't boot from SD card.

### ISSUE THREAD

**Issue by phineasthecat** [EliasKotlyar/Xiaomi-Dafang-Hacks#292]
Flashed the T20 Xiaofang cfw.bin, since the Wyze Cam V2 is identical except for a Wyze sticker as far as I can tell. All I got was the flashing yellow setup LED, so I hooked up a serial console and got the attached boot log:
[wyzecam_bootlog.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1945158/wyzecam_bootlog.txt)

After that, it boots the stock firmware, and goes into a boot loop after the stock firmware's watchdog fires.

Tried multiple SD cards and still get the same result.

**Comment by EliasKotlyar** [comment]
Hello @phineasthecat ,

I suppose that your wyzecam is having a diffent kind of firmware, which is not compatible to the kernel which is in the dafang. At least as i can tell, you have a more recent bootloader. Compare your bootlog with this bootlog:
https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/information/bootlog.md

Do you have dumped your original firmware? If so, i can try to create a WYZE V2 compatible image for you.

If you havent dumped the firmware:

There is still a way to recover. You can use the backup-partitions for getting access to the camera. Here is the partition layout:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/howto_modfirmware.md. 

Use following guide first to get root access trough serial:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/getroot.md
Then dump your firmware using following tutorial:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/firmware-dump.md
And afterwards provide your firmware files using a push-request. I can then create an original firmware out of it and also try to create a modified version.

**Comment by EliasKotlyar** [comment]
Hello @phineasthecat ,

Can you please try the new Firmware? I do not expect it to work without any issues, but it should at least boot into the CFW, because of the original kernel / rootfs. It not, please provide a bootlog, i can then try to find out the issue.

**Comment by phineasthecat** [comment]
Hey @EliasKotlyar, just sat down at my desk to try out the new cfw. Looks like mounting the SD card is still failing:
[wyze_cfw1.0_bootlog.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1953148/wyze_cfw1.0_bootlog.txt)

**Comment by phineasthecat** [comment]
So it looks setting the shell to /bin/sh in the uboot bootargs variable causes the kernel to not not populate /proc and /sys... Something must be happening in their linuxrc to trigger that? 

Note I CAN kill the iCamera process without the watchdog firing.

**Comment by openipcamera** [comment]
```
echo "Starting OpenIPC"
CONFIGPATH=/system/sdcard/config

## Update hostname:
hostname -F $CONFIGPATH/hostname.conf

## Load kernel modules
insmod /driver/tx-isp.ko isp_clk=100000000
##insmod /driver/sensor_imx323.ko
insmod /driver/sensor_jxf22.ko
##insmod /driver/sensor_ps5230.ko
insmod /driver/exfat.ko
insmod /driver/sample_motor.ko
insmod /driver/audio.ko spk_gpio=-1 sign_mode=0
insmod /driver/sinfo.ko
##insmod /driver/8189es.ko
insmod /driver/sample_pwm_core.ko
insmod /driver/sample_pwm_hal.ko
insmod /driver/rtl8189ftv.ko
##insmod /system/sdcard/driver/sensor_jxf22.ko data_interface=2 pwdn_gpio=-1 res                                                                    et_gpio=18 sensor_gpio_func=0

## Start Wifi:
wpa_supplicant -D nl80211 -iwlan0 -c $CONFIGPATH/wpa_supplicant.conf -B &
sleep 5
#udhcpc -i wlan0 -s /system/etc/udhcpc.script -q
udhcpc -i wlan0 -p /var/run/udhcpc.pid -b -x hostname:"$(hostname)"

## NTP Server
ntp_srv="$(cat "$CONFIGPATH/ntp_srv.conf")"

## Start FTP & SSH
/system/sdcard/bin/dropbearmulti dropbear -R
/system/sdcard/bin/bftpd -d

## Start Webserver:
/system/sdcard/bin/boa -c /system/sdcard/config/

## Autostart
for i in /system/sdcard/config/autostart/*; do
  $i
done
```

**Comment by openipcamera** [comment]
The binary singleboadtest in the wyze firmware mounts the sdcard properly on boot.
/system/bin/singleBoadTest
in appfs.bin

**Comment by phineasthecat** [comment]
@openipcamera 

Thanks for that info! singleBoadTest does indeed mount the sdcard.
 
Modifying rcfile.sh like so:
`# Set mdev`
`mount -t proc proc /proc`
`mount -t sysfs sys /sys`
`mount -t tmpfs tmpfs /dev`
`echo /sbin/mdev > /proc/sys/kernel/hotplug`
`/sbin/mdev -s && echo "mdev is ok......"`

and adding:
`/system/bin/singleBoadTest`
somewhere after mounting system and before attempting to mount the SD card should fix the SD card not mounting issue.

**Comment by EliasKotlyar** [comment]
Thanks @phineasthecat , I hope that now the support is completely established.
Can you tell me which features still have issues? I dont own a Wyzecam and cannot buy one that easily.

**Comment by MatthewNinety** [comment]
I used the image that openipcam created for the v2 alpha release and it works completely on my wyze v2.  Thanks Elias!
Matthew

**Comment by phineasthecat** [comment]
Yeah the Wyzecam v2 uses a different Realtek chipset for the wifi (rtl8189ftv vs. rtl8189 on the Xiaomi cameras.) I think everything else is the same? @openipcamera are the gpios for the LEDs/IR cut motor the same as on the Xiaomi cameras?

**Comment by UgleyBogley** [comment]
I know this is not the right area, but I have to ask.
I have a Wyzecam v2 (USA)
2 questions,
1, what is the purpose to hack it from what it already does? what are the benefits?
2. I have the rtl8189ftv Realtek chipset in mine. Was this issue resolved?

Sorry for the noob question (#1) but it had to be asked.
Thanks in advance!!

**Comment by ark-git** [comment]
I have two WyzeCams V2 and I have not been successful in installing . I placed the demo.bin file in the sdcard, held the setup button for around 6secs, see blue led on, release setup button, wait for blue button to turn to yellow, turn off cam, remove demo.bin and other folders from sdcard, copied all files from "firmware mod" onto SDcard , change wireless ssid and password, reinstall sdcard into cam, reapply power, see blue led turn on, then change to yellow, then go off, and then it starts over. When I first install the demo.bin and reboot I see the mac address registering on the router, I can ping it. I have installed OpenIPC build and its works. However having connectivity issues like RTSP streaming dropping connection to Blue Iris.

**Comment by jmtatsch** [comment]
What does your startup log say?

**Comment by jmtatsch** [comment]
Isn’t there a log directory on your sdcard?

**Comment by ark-git** [comment]
I will check tonight.

**Comment by ark-git** [comment]
From startup.log file
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
loaded common functions
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
Could not read interface wlan0 flags: No such device
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Could not read interface wlan0 flags: No such device
wlan0: Failed to initialize driver interface
udhcpc: 
initialized gpios
dropbear: 
bftpd: 
lighttpd: 
Startup finished!

**Comment by a2ng** [comment]
Same startup.log using my brand new Xiaofang 1s.

**Comment by jmtatsch** [comment]
@ark-git @a2ng as mentioned by @phineasthecat the new XiaoFangs/WyzeCams V2 seem to use rtl8189ftv wireless chipset vs. the rtl8189 in the dafangs. So you will likely need to comment the old in run.sh and load the other:
```
#insmod /driver/8189es.ko
insmod /driver/rtl8189ftv.ko
```

**Comment by a2ng** [comment]
thanks @jmtatsch i do modified run.sh ::

`## insmod /driver/8189es.ko rtw_initmac="$MAC"
insmod /driver/rtl8189ftv.ko rtw_initmac="$MAC"`

but startup.log still produce this ::

`
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
loaded common functions
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
Could not read interface wlan0 flags: No such device
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Could not read interface wlan0 flags: No such device
wlan0: Failed to initialize driver interface
udhcpc: 
initialized gpios
dropbear: 
bftpd: 
lighttpd: 
Startup finished!
`
i also try 'rtl8189ftv.ko' (rt L ) and 'rtl8189ftv.ko' (rt One ) and still same logs.

**Comment by a2ng** [comment]
sorry, heres corrected lines for run.sh ::
`insmod /driver/rtl8189ftv.ko rtw_initmac="$MAC"
`
and remark ::
`insmod /driver/8189es.ko rtw_initmac="$MAC"`

**Comment by ark-git** [comment]
@jmtatsch and @a2ng. This works. Thanks

**Comment by jmtatsch** [comment]
Great then we can probably do this automatically depending on which drivers are available on which platform 675554ffe854ca646b8d383c9def9386474294d8. Can someone ls /driver on a xiafang/wyzecam just to see if my assumption is correct?

**Comment by ark-git** [comment]
[root@WyzeMudroom:~]# ls /driver
audio.ko              sample_pwm_core.ko    sinfo.ko
exfat.ko              sample_pwm_hal.ko     tx-isp.ko
rtl8189ftv.ko         sample_speakerctl.ko
sample_motor.ko       sensor_jxf22.ko

**Comment by miyo31** [comment]
Hello,
Sorry but it seems I have same kind of problem with my Dafang.
Flashed a few months ago with cfw-1.2. Worked like a charm.
Then powered off for 2 months.
When I reboot last week, it didn't work, I mean I could not reach it on network, probably wifi problem, led was orange ( fixed) and not blue.
I decided to reflash using last hack with cfw-1.3.
I did not succeed, still not appears in my wifi network, does not get an IP on my router.
I used the same wpa_supplicant.conf that I used in the past.

Here's the startup.log:

==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directory
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
udhcpc: udhcpc (v1.22.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, forking to background
initialized gpios
dropbear: 
bftpd: 
lighttpd: 
Startup finished!




It's a DAFANG, in the back of this cam, I can read: , CMIT ID: 2017DP3894
Other info: DF3-00141751

In my several tries, I updated cam to official firmware 5.5.1.306 then reapply hack.
Same results downgrading to 5.5.1.177 ( using demo_5.5.1.177 in folder firmware_original )

I've spent many hours on trying different solutions ( change microsd, wifi conf simplified, several firmwares 1.0 1.1 etc .. ) but I did not succeed.

Thanks in advance if you've got an idea,

Best Regards,

Emilio

**Comment by jmtatsch** [comment]
Can we close this issue now?

**Comment by ark-git** [comment]
Yes. I have not tried the latest Image yet, however by using @a2ng instructions above I was able to get it working.

**Comment by reishigupta** [comment]
Using DaFang Camera, not able to connect to wifi, startup.log shows this:


Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
udhcpc: deleting routers
adding dns 103.56.229.130
adding dns 103.56.228.140
Initialized gpios
dropbear: 
bftpd: 
lighttpd: 
Startup finished!



Please help.
