### ISSUE TITLE
MQTT Commands not working, neither status change is working 

### ISSUE THREAD

**Issue by TheCrey** [EliasKotlyar/Xiaomi-Dafang-Hacks#509]
Hi, 

I hope you can help me out here. 
Days ago, while still playing with the FW etc etc it was working. 
Now it does not work anymore. 

i see the following error messages in the mqtt broker log

1529698229: New connection from 192.168.1.28 on port 1883.
1529698229: New client connected from 192.168.1.28 as mosqpub|19361-dafang01 (c1, k60, u'dafang').
1529698229: Client mosqpub|19361-dafang01 disconnected.
1529698229: New connection from 192.168.1.28 on port 1883.
1529698229: New client connected from 192.168.1.28 as mosqpub|19369-dafang01 (c1, k60, u'dafang').
1529698229: Client mosqpub|19369-dafang01 disconnected.
1529698229: New connection from 192.168.1.28 on port 1883.
1529698229: New client connected from 192.168.1.28 as mosqpub|19377-dafang01 (c1, k60, u'dafang').
1529698229: Client mosqpub|19377-dafang01 disconnected.
1529698229: New connection from 192.168.1.28 on port 1883.
1529698229: New client connected from 192.168.1.28 as mosqpub|19399-dafang01 (c1, k60, u'dafang').
1529698229: Client mosqpub|19399-dafang01 disconnected.
1529698229: New connection from 192.168.1.28 on port 1883.
1529698229: New client connected from 192.168.1.28 as mosqpub|19416-dafang01 (c1, k60, u'dafang').
1529698229: Client mosqpub|19416-dafang01 disconnected.
1529698230: New connection from 192.168.1.28 on port 1883.
1529698230: New client connected from 192.168.1.28 as mosqpub|19448-dafang01 (c1, k60, u'dafang').
1529698230: Client mosqpub|19448-dafang01 disconnected.

All other MQTT devices (Sonoff) are working fine. 

I am on Hass.io, using version 0.71. and the internal mqtt broker (which worked before) version 1.0 
Already did a reboot of home assistant and of the mqtt control and status server, no luck

Anyone any idea ?

Cheers

**Comment by jmtatsch** [comment]
Internal broker  never really worked for me. Run the mosquitto one.

**Comment by TheCrey** [comment]
Sorry misunderstanding, I run the 

Mosquitto broker 1.0

**Comment by fliphess** [comment]
I think I have the same issue. 

In the webserver logs it looks the curl request to `action.cgi` redirects to https.

I changed the url from `http://` to `https://` in https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/scripts/mqtt-control.sh#L183 and added `-k` to the mqtt curl opts in `mqtt.conf` but i'm still experiencing some authentication issues.

**Comment by jmtatsch** [comment]
Should be fixed in #510. Thanks @fliphess

**Comment by TheCrey** [comment]
So, please allow me one simple question, as it is fixed now, how can I get the fixed version now ? 
Do I need to download the files again or would be an update enough ? (over the menu) 

Sorry I am not that familiar with github and the exact working method.

**Comment by jmtatsch** [comment]
If you have a fairly recent version webupdate should work fine. If you have a version where it’s broken update manually from the repository.

**Comment by TheCrey** [comment]
I did the web update, and checked the mqtt-control.sh it does have now the fix, as far as I understood, only line 183, needed a change. 

It is still not working, should completely reinstall ? 
I still have the same issues as mentioned before.

**Comment by jmtatsch** [comment]
Did you reset/reboot the Mqtt broker?

**Comment by TheCrey** [comment]
Yes, also double checked if connection is available. 
Also restarted the cam, and restarted the broker again. 
No luck at all. 

I do not know why it was working before, even before the fix, and why know not longer

**Comment by jmtatsch** [comment]
SSH to your camera. Use the mosquitto binary to publish a msg to your broker on the console, then you should see some errors. Possibly there is also a verbose flag.

**Comment by TheCrey** [comment]
I am sorry.. I know how to ssh, but I do not know how to publish manually a msg. 
I only can say that the other sonoff mqtt devices are working fine.

**Comment by TheCrey** [comment]
The log file does not show a lot in hassio (no status change etc, just that a device is connected), also I am not quite sure how to do that, to execute it one by one. 

So I will set up a new Mosquitto broker on a new pi, to see if this is working or not.
Also with a new broker I should be able to see exactly what is coming and what not. 

What I found out also ist that, after is restart the broker and or the cam, the new status is not published too. 
A simple ping is working fine (just to be sure I do have a connection)

**Comment by ds4213** [comment]
> a lot in hassio (no status change etc, just that a device is connected), also I am not quite sure how to do that, to execute it one by one.
> 
> So I will set up a new Mosquitto broker on a new pi, to see if this is working or not.
> Also with a new broker I s

hi did you get it resolved?

**Comment by sanjeewasam** [comment]
I am having the same issue. I have 3 units. All flashed with new firmware - 2 Dafangs and one xiofang. Running Hass.io and Mosquito broker. No errors from all Sonoff/Tasmota and Multi-Sensor nodes based on nodeMCUs

**Comment by cristimi** [comment]
I am having the same issue as well while running Hassio 0.83.3 and Mosquito broker.  Has anyone found a solution / workaround yet?

**Comment by MichaelRoxin** [comment]
same here. I have been runnig Hassbian before with no problem. But now in hassio Dafang Mqtt dont work. 

Shelly 1 do work. I have the Mosquitto add on and have the same in configuration.yaml as before. 

My add on i have this {
  "logins": [],

But i configurations.yaml I have my user and password 

My log says : 1550833326: New client connected from 10.0.1.16 as mosqpub|18263-DAFANG (c1, k60, u'michael').
1550833326: Client mosqpub|18263-DAFANG disconnected.

**Comment by fliphess** [comment]
The logs will show many connects and disconnects from the camera as it sends every message using a new mqtt connection. Don't worry about that.

What is not working using hassio? Do you receive any messages from the camera? 

You can check for incoming messages on the mqtt server using the `mosquitto-sub` utility:

```
mosquitto_sub -h "$MQTT_SERVER" -p "$PORT" -u "$USER" -P "$PASS" -t "$TOPIC" -v
```

This will create a connection to the server listening on the given topic. If you do not receive that much messages, you can check by connecting to the root, showing all topics. Use topic `#` to do this.

**Comment by fliphess** [comment]
Btw, are you using the internal/inbuild mosquitto server of hassio?  I recommend using mosquitto, which is a bit more versatile.

**Comment by MichaelRoxin** [comment]
I use the addon mosquitto. 

Before I hade mosquitto setup on hassbian. I thought that was the same thing. 

I get alot when subscribe to # with mqtt.fx

**Comment by MichaelRoxin** [comment]
Now I even did a full update on the sd card. No change. 

the add-on config looks like this 
{
  "logins": [],
  "anonymous": false,
  "customize": {
    "active": false,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}

And my configuration.yaml
mqtt:
  broker: 10.0.1.40
  username: xxxxx
  password: xxxxx
  discovery: true 
  discovery_prefix: homeassistant

and mqtt.conf

# Options for mosquitto_sub & mosquitto_pub                      
USER=xxxxx                                                   
PASS=xxxxx                           
HOST=10.0.x.xx same as PI                
PORT=1883     
              
# Define a location
LOCATION="Garage"  
                   
# Define device name
DEVICE_NAME="dafang"
                    
# Define the base topic used by the camera
# send a message to myhome/dafang/set with the payload help for help.
# Results will be placed in myhome/dafang/${command} or topic/dafang/error - so
TOPIC="$LOCATION/$DEVICE_NAME"                                                 
                                                                               
# Define an autodiscovery prefix, if autodiscovery is desired:                 
AUTODISCOVERY_PREFIX="homeassistant"
