### ISSUE TITLE
Services will not load

### ISSUE THREAD

**Issue by manianac** [EliasKotlyar/Xiaomi-Dafang-Hacks#518]
I have new out of box Wyze Cam v2's that I am trying to set up.  I'm using cfw-1.1 as demo.bin to flash, and that works fine.  I then load the modded files to the sdcard in the firmware_mod folder.

I've set up wpa_supplicant.conf, and it connects to my router fine.  RTSP is working, I have a stream, but I have no http/https services (ports are refused).  SSH&FTP connect, but won't accept 'ismart12' as a password.

Startup log:
```
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
udhcpc: deleting routers
adding dns 192.168.20.1
Initialized gpios
dropbear: 
bftpd: 
lighttpd: 
Startup finished!
```
crond.log
```
crond: time disparity of 25496665 minutes detected
crond: crond (busybox 1.29.0.git) started, log level 8
crond: time disparity of 25496684 minutes detected
crond: USER root pid 262 cmd busybox run-parts /system/sdcard/config/cron/periodic/15min
crond: USER root pid 267 cmd busybox run-parts /system/sdcard/config/cron/periodic/15min
crond: USER root pid 268 cmd busybox run-parts /system/sdcard/config/cron/periodic/hourly
crond: USER root pid 273 cmd busybox run-parts /system/sdcard/config/cron/periodic/15min
crond: USER root pid 274 cmd busybox run-parts /system/sdcard/config/cron/periodic/15min
crond: USER root pid 284 cmd busybox run-parts /system/sdcard/config/cron/periodic/15min
crond: USER root pid 291 cmd busybox run-parts /system/sdcard/config/cron/periodic/15min
crond: USER root pid 292 cmd busybox run-parts /system/sdcard/config/cron/periodic/hourly
crond: USER root pid 296 cmd busybox run-parts /system/sdcard/config/cron/periodic/15min
```
log
```
================== START ===============
/system/sdcard/bin/v4l2rtspserver-master  -E MP3:44100   
2018-06-24 04:44:04.347 (   0.003s) [main thread     ]               main.cpp:443      0| === Dumping environment variables ===
2018-06-24 04:44:04.348 (   0.004s) [main thread     ]               main.cpp:446      0| USER=root
2018-06-24 04:44:04.348 (   0.004s) [main thread     ]               main.cpp:446      0| LD_LIBRARY_PATH=/system/sdcard/lib/:/thirdlib:/system/lib
2018-06-24 04:44:04.348 (   0.004s) [main thread     ]               main.cpp:446      0| SHLVL=2
2018-06-24 04:44:04.348 (   0.005s) [main thread     ]               main.cpp:446      0| HOME=/
2018-06-24 04:44:04.349 (   0.005s) [main thread     ]               main.cpp:446      0| OLDPWD=/sys/class/gpio
2018-06-24 04:44:04.349 (   0.005s) [main thread     ]               main.cpp:446      0| TERM=vt102
2018-06-24 04:44:04.349 (   0.005s) [main thread     ]               main.cpp:446      0| PATH=/system/bin:/bin:/sbin:/usr/bin:/usr/sbin
2018-06-24 04:44:04.349 (   0.005s) [main thread     ]               main.cpp:446      0| SHELL=/bin/sh
2018-06-24 04:44:04.349 (   0.006s) [main thread     ]               main.cpp:446      0| PWD=/sys/class/gpio/gpio77
2018-06-24 04:44:04.350 (   0.006s) [main thread     ]               main.cpp:446      0| rmem=16M@0x7000000
2018-06-24 04:44:04.350 (   0.006s) [main thread     ]               main.cpp:449      0| === end ===
2018-06-24 04:44:06.471 (   2.128s) [main thread     ]         ImpEncoder.cpp:1185     0| Found Sensor with ID:22
2018-06-24 04:44:07.120 (   2.777s) [main thread     ]         ImpEncoder.cpp:1423     0| encoderMode: 2
2018-06-24 04:44:07.121 (   2.777s) [main thread     ]         ImpEncoder.cpp:1462     0| Using VBR mode.
2018-06-24 04:44:07.121 (   2.777s) [main thread     ]         ImpEncoder.cpp:1467     0| Set initial bitrate (from sharedmem) to 5000
i264e[info]: profile Constrained Baseline, level 3.1
2018-06-24 04:44:07.139 (   2.795s) [main thread     ]         ImpEncoder.cpp:123      0| OSD pos 0,0,1279,36
2018-06-24 04:44:07.140 (   2.796s) [main thread     ]         ImpEncoder.cpp:123      0| OSD pos 1240,0,1279,39
2018-06-24 04:44:08.153 (   3.809s) [DeviceSource    ]       DeviceSource.cpp:91       0| begin thread
2018-06-24 04:44:08.159 (   3.815s) [main thread     ]               main.cpp:557      0| Create ALSA Source.../dev/dsp
2018-06-24 04:44:08.159 (   3.816s) [main thread     ]        ALSACapture.cpp:94       0| Audio In GetPubAttr samplerate : 8000
2018-06-24 04:44:08.160 (   3.816s) [main thread     ]        ALSACapture.cpp:95       0| Audio In GetPubAttr   bitwidth : 16
2018-06-24 04:44:08.160 (   3.816s) [main thread     ]        ALSACapture.cpp:96       0| Audio In GetPubAttr  soundmode : 1
2018-06-24 04:44:08.160 (   3.816s) [main thread     ]        ALSACapture.cpp:97       0| Audio In GetPubAttr     frmNum : 40
2018-06-24 04:44:08.160 (   3.816s) [main thread     ]        ALSACapture.cpp:98       0| Audio In GetPubAttr  numPerFrm : 1600
2018-06-24 04:44:08.160 (   3.816s) [main thread     ]        ALSACapture.cpp:99       0| Audio In GetPubAttr     chnCnt : 1
2018-06-24 04:44:08.161 (   3.817s) [update_thread   ]         ImpEncoder.cpp:413      0| Attempt to changed Bitrate to 5000
2018-06-24 04:44:08.161 (   3.817s) [update_thread   ]         ImpEncoder.cpp:431      0| Setting VBR maxBitrate.
2018-06-24 04:44:08.161 (   3.818s) [update_thread   ]         ImpEncoder.cpp:511      0| Changed motion sensitivity=4
2018-06-24 04:44:08.162 (   3.818s) [update_thread   ]         ImpEncoder.cpp:652      0| Detection region= ((0,0)-(1279,719))
2018-06-24 04:44:08.165 (   3.821s) [update_thread   ]         ImpEncoder.cpp:516      0| Changed motion region
2018-06-24 04:44:08.165 (   3.822s) [update_thread   ]         ImpEncoder.cpp:524      0| Display motion OSD color=2
2018-06-24 04:44:08.573 (   4.230s) [main thread     ]        ALSACapture.cpp:126      0| Audio In GetChnParam usrFrmDepth : 20
2018-06-24 04:44:08.574 (   4.230s) [main thread     ]        ALSACapture.cpp:154      0| Audio In GetVol    vol : 70
2018-06-24 04:44:08.723 (   4.379s) [main thread     ]        ALSACapture.cpp:379      0| Enabled highfilter
2018-06-24 04:44:08.723 (   4.380s) [main thread     ]        ALSACapture.cpp:396      0| NS Filter=1
2018-06-24 04:44:08.798 (   4.455s) [DeviceSource    ]       DeviceSource.cpp:91       0| begin thread
2018-06-24 04:44:08.799 (   4.455s) [DeviceSource    ]        ALSACapture.cpp:379      0| Enabled highfilter
2018-06-24 04:44:08.799 (   4.456s) [DeviceSource    ]        ALSACapture.cpp:396      0| NS Filter=1
2018-06-24 04:44:08.807 (   4.463s) [main thread     ]               main.cpp:152      0| Play this stream using the URL "rtsp://192.168.20.128:8554/unicast"
2018-06-24 04:47:38.475 ( 214.132s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 04:47:38.519 ( 214.175s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 04:47:38.519 ( 214.176s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 04:47:40.513 ( 216.169s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 04:47:40.552 ( 216.208s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-06-24 04:47:44.637 ( 220.293s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 04:47:44.653 ( 220.310s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 04:47:44.654 ( 220.310s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 04:47:46.673 ( 222.330s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 04:47:46.691 ( 222.348s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-06-24 05:11:43.349 (1659.005s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 05:11:43.377 (1659.033s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 05:11:43.377 (1659.034s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 05:11:45.387 (1661.043s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 05:11:45.406 (1661.063s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-06-24 05:12:42.548 (1718.204s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 05:12:42.564 (1718.221s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 05:12:42.565 (1718.221s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 05:12:44.584 (1720.241s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 05:12:44.603 (1720.260s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-06-24 05:13:16.025 (1751.681s) [main thread     ]ServerMediaSubsession.c:25       0| Creating Source...
2018-06-24 05:13:16.025 (1751.682s) [main thread     ]ServerMediaSubsession.c:29       0| Creating H264 Source...
2018-06-24 05:13:16.026 (1751.682s) [main thread     ]ServerMediaSubsession.c:51       0| Creating Sink for format : video/H264
2018-06-24 05:13:16.027 (1751.683s) [main thread     ]ServerMediaSubsession.c:25       0| Creating Source...
2018-06-24 05:13:16.027 (1751.683s) [main thread     ]ServerMediaSubsession.c:42       0| Creating normal Source...
2018-06-24 05:13:16.027 (1751.684s) [main thread     ]ServerMediaSubsession.c:51       0| Creating Sink for format : audio/MPEG
2018-06-24 05:13:16.037 (1751.694s) [main thread     ]ServerMediaSubsession.c:25       0| Creating Source...
2018-06-24 05:13:16.038 (1751.694s) [main thread     ]ServerMediaSubsession.c:29       0| Creating H264 Source...
2018-06-24 05:13:16.038 (1751.694s) [main thread     ]ServerMediaSubsession.c:51       0| Creating Sink for format : video/H264
2018-06-24 05:13:16.041 (1751.698s) [main thread     ]ServerMediaSubsession.c:25       0| Creating Source...
2018-06-24 05:13:16.042 (1751.698s) [main thread     ]ServerMediaSubsession.c:42       0| Creating normal Source...
2018-06-24 05:13:16.042 (1751.699s) [main thread     ]ServerMediaSubsession.c:51       0| Creating Sink for format : audio/MPEG
RTCPInstance::RTCPInstance error: totSessionBW parameter should not be zero!
RTCPInstance::RTCPInstance error: totSessionBW parameter should not be zero!
2018-06-24 05:13:28.041 (1763.697s) [main thread     ]       DeviceSource.cpp:110      0| V4L2DeviceSource::doStopGettingFrames
2018-06-24 05:13:28.041 (1763.697s) [main thread     ]       DeviceSource.cpp:110      0| V4L2DeviceSource::doStopGettingFrames
2018-06-24 05:13:28.042 (1763.698s) [main thread     ]       DeviceSource.cpp:110      0| V4L2DeviceSource::doStopGettingFrames
2018-06-24 05:13:28.042 (1763.698s) [main thread     ]       DeviceSource.cpp:110      0| V4L2DeviceSource::doStopGettingFrames
2018-06-24 05:46:04.505 (3720.161s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 05:46:04.524 (3720.180s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 05:46:04.524 (3720.180s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 05:46:06.555 (3722.212s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 05:46:06.597 (3722.253s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-06-24 05:46:14.701 (3730.358s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 05:46:14.720 (3730.377s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 05:46:14.721 (3730.377s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 05:46:16.756 (3732.413s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 05:46:16.795 (3732.451s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-06-24 05:46:49.418 (3765.074s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 05:46:49.438 (3765.094s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 05:46:49.438 (3765.094s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 05:46:51.461 (3767.118s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 05:46:51.480 (3767.136s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-06-24 06:12:58.755 (5334.411s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 06:12:58.777 (5334.433s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 06:12:58.777 (5334.433s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 06:13:00.799 (5336.456s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 06:13:00.831 (5336.488s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-06-24 06:15:42.115 (5497.772s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 06:15:42.143 (5497.800s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 06:15:42.144 (5497.800s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 06:15:44.148 (5499.804s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 06:15:44.166 (5499.823s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-06-24 06:18:51.933 (5687.589s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 06:18:51.952 (5687.608s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 06:18:51.952 (5687.609s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 06:18:53.975 (5689.631s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 06:18:53.995 (5689.651s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-06-24 06:22:24.238 (5899.894s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-24 06:22:24.280 (5899.936s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:0
2018-06-24 06:22:24.280 (5899.937s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-24 06:22:26.317 (5901.973s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-24 06:22:26.339 (5901.996s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
```
I will say all my cameras work fine with "OpenIPC" project, which is an older version of this I believe.  But I can't seem to find why this one won't load.

**Comment by jmtatsch** [comment]
I think the password issue should have been fixed a couple commits ago with #485. 
Can you check you are running the latest code?

**Comment by manianac** [comment]
Verified I'm on commit 38e167f, currently trying to see if I can add more verbosity to the logs.

**Comment by jmtatsch** [comment]
Possibly these are two separate issues. 
1. Wyze Cam v2 has different default passwords which should have been mitigated via #485.
@tssva Do you have an idea what may be the culprit?
2. And your ssl certificate probably was not generated successfully.

**Comment by manianac** [comment]
I have tried two different brand of sd cards, verified issue is still present.  I have dis-allowed remounting of /etc, and it will now connect to http (no https), and SSH will work.

Just throwing suggestions out, but the original `/etc/passwd` and `/etc/shadow` are 0600 permissions, while the remounted sdcard ones are 0755 due to the vfat filesystem.  Is it possible the kernel is refusing to read it?

**Comment by jorgemonteiro** [comment]
I have exactly the same problem you are having but with a brand new Wyze Pan. I have another Wyze Pan that is working fine, but this one is not :(

Did you ever figure out what is the problem?

Thanks!

**Comment by manianac** [comment]
No, but as i said I reverted to an earlier commit, that booted fine, than auto-updated.

**Comment by jorgemonteiro** [comment]
Yeah, just did the same and it now works fine. I guess I should not have updated my local repo before patching the new camera :)

**Comment by manianac** [comment]
Workaround stated, but cause is unknown
