### ISSUE TITLE
mqtt-control reads the messages it sends

### ISSUE THREAD

**Issue by jboeddeker** [EliasKotlyar/Xiaomi-Dafang-Hacks#675]
mqtt-control.sh listens to $TOPIC/# while it sends messages the same topic. So, whenever a control message is received, the just-sent answer is also received and read. 

According to my opinion, it would be better configure the server to listen to a special control topic $TOPIC/control/#, then it could ignore all the status messages it is sending by itself. 

I am able to change this, but i do not know if that separation of in/out queue is possible with all smarthome systems. I only use openHAB with that it would be fine.

Another option would be to include all known command topics to the mosquitto_sub -t parameter, but this would be quite a list and not really maintainable.

**Comment by jmtatsch** [comment]
First option seems alright. Can you whip up a PR?

**Comment by jboeddeker** [comment]
Yes. I will use the $TOPIC/control.

**Comment by jboeddeker** [comment]
The problem is the performance. Every status message and every answer triggers the switch statement with its 30 something cases and causes another invocation of mosquitto_sub. If you send several commands you will notice a delay.

Add an echo $line in the control loop and execute mqtt-control.sh in a shell. Nothing wrong is happening, just too much unnecessary stuff.

**Comment by jmtatsch** [comment]
I understand your concerns now and agree.
But when we are changing the api at all I would like to take the opportunity to make it more simple and consistent. I will make a pull request soon and request for feedback.

**Comment by guandalf** [comment]
Hi,

I am available to give it a try on Home Assistant, if this can help.

TY

**Comment by jmtatsch** [comment]
@guandalf that would be swell.

**Comment by guandalf** [comment]
I applied the patch but I get:

[root@DAFANG:sdcard]# /system/sdcard/bin/busybox /system/sdcard/scripts/mqtt-control.sh
mqtt-control.sh: applet not found

running mqtt-control I had no time to investigate yet.
Trying tonight.

**Comment by jboeddeker** [comment]
@guandalf, could you tell me how you did apply the the patch? Thanks.

**Comment by guandalf** [comment]
I downloaded the patch from the pull request:
wget https://patch-diff.githubusercontent.com/raw/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/677.patch

I removed some junk with vi, then:
patch -p1 < 677.patch
on a local copy of the repo and I "uploaded" the patched files pasting them with vi.

**Comment by jmtatsch** [comment]
@guandalf missing a nohup?

**Comment by jboeddeker** [comment]
I did the following: I replaced the REPO variable in the autoupdate.sh script with my repository and started autoupdate.sh.

Worked as expected.

**Comment by guandalf** [comment]
Done the same but it seems not to be working here. I'll try again later on tonight.

**Comment by bachya** [comment]
I'm a HASS user, as well – I'll apply #677 and see what I find.

**Comment by bachya** [comment]
Follow-up: no change. Here are the steps I followed:

1. SSHed into the camera.
2. Moved `/system/sdcard/scripts/mqtt-autodiscovery.sh` to `/system/sdcard/scripts/mqtt-autodiscovery.sh.original`.
3. Moved `/system/sdcard/scripts/mqtt-control.sh` to `/system/sdcard/scripts/mqtt-autodiscovery.sh.control`.
4. Copied the PR's version of `mqtt-autodiscovery.sh` into place (`wget https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/7021cdc05c5e67fcf153a9921e6443bfa2f11744/firmware_mod/scripts/mqtt-autodiscovery.sh`).
4. Copied the PR's version of `mqtt-control.sh` into place (`wget https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/7021cdc05c5e67fcf153a9921e6443bfa2f11744/firmware_mod/scripts/mqtt-control.sh`).
5. Rebooted the camera.
6. Restarted Home Assistant.
7. Home Assistant continues to show a timeout when attempting to retrieve the RTSP stream.

By comparison, when I disable both of the MQTT services and reboot the camera, the RTSP stream immediately appears in Home Assistant.

**Comment by guandalf** [comment]
@jmtatsch nohup is just to put it in the background. I wanted to see the output on the console.

**Comment by bachya** [comment]
@guandalf Are you confirming that the PR doesn't resolve the issue (and that I merely included too many steps in the reproduction)?

**Comment by guandalf** [comment]
@bachya exactly. I tested both applying the patch myself and installing @jboeddeker repo with the updater.
In my case the first attempt ended up in mqtt-control not starting anymore.
The second attempt resulted in mqtt working while rtsp was not working and vice versa.

Sorry.

**Comment by bachoo786** [comment]
I am facing the same issue when I turn mqtt on and the stream on home assistant just disappears and goes off.

Any help would be appreciated please.

Thanks.

**Comment by humpedli** [comment]
The mentioned HA issue is a different problem, please see my latest comments on #436. I think calling `mosquitto_pub.bin` causes the issue and it doesn't matter how and it should be updated with the current version of mosquitto, but I am not sure and don't know how to do it.

I saw your issue and PR, I think it's OK however I think you don't have to add `/control` topic to every case, just remove the cases which are not containing `/set `ending and the the just-sent status answer won't trigger anything again.

Anyway this PR won't solve the other issue (#436), but it will improve the messaging.

**Comment by jmtatsch** [comment]
@humpedli Thank you for your analysis. Maybe you can try a fresher mosquitto_pub.bin from https://github.com/anmaped/openfang ?

**Comment by humpedli** [comment]
@jmtatsch I think I am noob, I didn't find any `mosquitto_pub.bin` in the referenced repository. I downloaded the **toolchain-0d1384c.tar.xz** release archive also, but I found only `mosquitto_pub` file without `.bin` extension.  Camera has both files (with `.bin` and without `.bin`). Replacing that file on the camera didn't solve the issue. Could you please help me to find the mentioned `.bin` file? Thank you.
